<a href="https://colab.research.google.com/github/badhayearushi-alt/Python---Basic---Projects/blob/main/14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 5x6 array with random integers between 10 and 100
arr = np.random.randint(10, 101, (5, 6))

print("Array:")
print(arr)

print("\nShape of array:", arr.shape)
print("Total number of elements:", arr.size)
print("Data type:", arr.dtype)

Array:
[[71 89 96 12 30 74]
 [23 55 43 15 98 76]
 [83 91 23 69 12 54]
 [44 26 74 34 89 83]
 [58 53 32 32 22 69]]

Shape of array: (5, 6)
Total number of elements: 30
Data type: int64


In [ ]:
import numpy as np

# Generate 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

print("Array:")
print(arr)

print("\nMinimum value:", np.min(arr))
print("Index of minimum value:", np.argmin(arr))

print("\nMaximum value:", np.max(arr))
print("Index of maximum value:", np.argmax(arr))

print("\nSum of all elements:", np.sum(arr))

print("Mean:", np.mean(arr))

print("Standard Deviation:", np.std(arr))

Array:
[12  7  3 22 39 25 21 33 31  2  5 11 14 24 24 29  7  2  3 45]

Minimum value: 2
Index of minimum value: 9

Maximum value: 45
Index of maximum value: 19

Sum of all elements: 359
Mean: 17.95
Standard Deviation: 12.85486289308447


In [ ]:
import numpy as np

# Create a 4x5 matrix with random integers between 20 and 80
matrix = np.random.randint(20, 81, (4, 5))

print("Matrix:")
print(matrix)

print("\nMinimum value:", np.min(matrix))
print("Maximum value:", np.max(matrix))

print("Sum of all elements:", np.sum(matrix))

print("Mean:", np.mean(matrix))

print("Standard Deviation:", np.std(matrix))

print("\nSum of each row:")
print(np.sum(matrix, axis=1))

print("\nSum of each column:")
print(np.sum(matrix, axis=0))

Matrix:
[[79 68 51 34 69]
 [73 38 53 31 57]
 [20 28 40 51 30]
 [69 22 68 26 48]]

Minimum value: 20
Maximum value: 79
Sum of all elements: 955
Mean: 47.75
Standard Deviation: 18.313587851647203

Sum of each row:
[301 252 169 233]

Sum of each column:
[241 156 212 142 204]


In [ ]:
import numpy as np

# Create a 1D array from 1 to 24
arr = np.arange(1, 25)

print("Original Array:")
print(arr)
print("Shape:", arr.shape)

# Reshape into (4,6)
a = arr.reshape(4, 6)
print("\nReshape (4,6):")
print(a)
print("Shape:", a.shape)

# Reshape into (3,8)
b = arr.reshape(3, 8)
print("\nReshape (3,8):")
print(b)
print("Shape:", b.shape)

# Reshape into (2,3,4)
c = arr.reshape(2, 3, 4)
print("\nReshape (2,3,4):")
print(c)
print("Shape:", c.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Reshape (4,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshape (3,8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshape (2,3,4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [ ]:
import numpy as np

# Create a 5x5 matrix
arr = np.random.randint(1, 101, (5, 5))

print("Original Matrix:")
print(arr)

# Diagonal elements
print("\nDiagonal Elements:")
print(np.diag(arr))

# Elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace elements less than 30 with 0
arr[arr < 30] = 0

print("\nModified Matrix:")
print(arr)

Original Matrix:
[[ 8  2 99 68 17]
 [95 48 49 92 72]
 [36 60 76 87 18]
 [81 19 37 93 93]
 [81 50 49  5 63]]

Diagonal Elements:
[ 8 48 76 93 63]

Elements Greater Than 50:
[99 68 95 92 72 60 76 87 81 93 93 81 63]

Modified Matrix:
[[ 0  0 99 68  0]
 [95 48 49 92 72]
 [36 60 76 87  0]
 [81  0 37 93 93]
 [81 50 49  0 63]]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nPower (**):")
print(a ** b)

print("\nModulo (%):")
print(a % b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Power (**):
[     10     400   27000 2560000]

Modulo (%):
[0 0 0 0]


In [ ]:
import numpy as np

# Generate marks for 10 students and 5 subjects
marks = np.random.randint(30, 101, (10, 5))

print("Student Marks:")
print(marks)

# Total marks
total = np.sum(marks, axis=1)

# Average marks
average = np.mean(marks, axis=1)

print("\nTotal Marks:")
print(total)

print("\nAverage Marks:")
print(average)

# Highest and Lowest scorer
highest = np.argmax(total)
lowest = np.argmin(total)

print("\nTop Student Index:", highest)
print("Top Student Total:", total[highest])

print("\nLowest Student Index:", lowest)
print("Lowest Student Total:", total[lowest])

print("\nOverall Class Mean:", np.mean(marks))
print("Overall Class Standard Deviation:", np.std(marks))

print("\nTop 3 Students Marks:")
top3 = np.argsort(total)[-3:]
print(marks[top3])

Student Marks:
[[48 52 84 54 99]
 [91 70 85 78 58]
 [47 73 77 35 79]
 [97 47 47 54 54]
 [48 74 61 79 48]
 [67 84 37 66 50]
 [96 87 65 78 53]
 [68 85 37 39 75]
 [85 32 43 30 70]
 [99 56 90 62 47]]

Total Marks:
[337 382 311 299 310 304 379 304 260 354]

Average Marks:
[67.4 76.4 62.2 59.8 62.  60.8 75.8 60.8 52.  70.8]

Top Student Index: 1
Top Student Total: 382

Lowest Student Index: 8
Lowest Student Total: 260

Overall Class Mean: 64.8
Overall Class Standard Deviation: 19.155155963865187

Top 3 Students Marks:
[[99 56 90 62 47]
 [96 87 65 78 53]
 [91 70 85 78 58]]


In [ ]:
import numpy as np

# Generate a 6x6 matrix of random numbers
matrix = np.random.randn(6, 6)

# Display the original matrix
print("Original Matrix:")
print(matrix)

# Print array properties
print("\nShape :", matrix.shape)
print("Size  :", matrix.size)
print("Data Type :", matrix.dtype)

# Find the index of maximum and minimum values
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
min_index = np.unravel_index(np.argmin(matrix), matrix.shape)

print("\nIndex of Maximum Value :", max_index)
print("Index of Minimum Value :", min_index)

# Extract the top-left 3x3 submatrix
print("\nTop-left 3x3 Submatrix:")
print(matrix[:3, :3])

# Replace all negative values with their absolute values
matrix[matrix < 0] = np.abs(matrix[matrix < 0])

# Display the modified matrix
print("\nModified Matrix:")
print(matrix)

# Print the mean of the modified matrix
print("\nMean of Modified Matrix :", np.mean(matrix))

Original Matrix:
[[ 2.66339669  1.20091444  0.57268847  2.58657374  0.06377275  2.32442854]
 [-0.6136832  -1.16871581 -0.31850336  1.71960216 -0.29185173  1.41477827]
 [ 0.17645484  0.77480655  0.0458304  -0.45846442 -0.5448953  -1.56473612]
 [-0.22361041 -0.99471578 -0.97912392  0.16023204  0.15364599 -1.73145475]
 [ 0.70188801 -0.10259523  0.21128871 -1.62499272 -0.55467863 -0.43299363]
 [-0.7284025   0.55234365 -1.11784713 -0.47722704 -0.28702005  2.04675521]]

Shape : (6, 6)
Size  : 36
Data Type : float64

Index of Maximum Value : (np.int64(0), np.int64(0))
Index of Minimum Value : (np.int64(3), np.int64(5))

Top-left 3x3 Submatrix:
[[ 2.66339669  1.20091444  0.57268847]
 [-0.6136832  -1.16871581 -0.31850336]
 [ 0.17645484  0.77480655  0.0458304 ]]

Modified Matrix:
[[2.66339669 1.20091444 0.57268847 2.58657374 0.06377275 2.32442854]
 [0.6136832  1.16871581 0.31850336 1.71960216 0.29185173 1.41477827]
 [0.17645484 0.77480655 0.0458304  0.45846442 0.5448953  1.56473612]
 [0.22361041

In [ ]:
import numpy as np

# Create Matrix A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create Matrix B
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nElement-wise Multiplication:")
print(A * B)

print("\nMatrix Multiplication:")
print(np.dot(A, B))

print("\nDifference:")
print("* performs element-wise multiplication.")
print("np.dot() performs matrix multiplication.")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Difference:
* performs element-wise multiplication.
np.dot() performs matrix multiplication.


In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# Display the original array
print("Original Array:")
print(arr)

# Extract first row
print("\nFirst Row:")
print(arr[0])

# Extract last column
print("\nLast Column:")
print(arr[:, 3])

# Extract center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[1:3, 1:3])

# Extract all even numbers using boolean indexing
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]
