<a href="https://colab.research.google.com/github/badhayearushi-alt/Python---Basic---Projects/blob/main/project_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# a) Create 1D array
arr1 = np.array([10,20,30,40,50])

# b) Create a 2D array
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
# Print 1D Array
print("1D Array:")
print(arr1)
print("Shape:",arr1.shape)
print("Data Type:",arr1.dtype)

# Print 2D Array
print("\n 2D Array")
print(arr2)
print("Shape:",arr2.shape)
print("Data Type:",arr2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

 2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [ ]:
import numpy  as np

# a) 1D array of 8 zeros
a = np.zeros(8)

# b) 2D array of shape (4,4) filled with one
b = np.ones((4,4))

# c) 3x3 matrix of zeros
c = np.zeros((3,3))

# Print array with proper label

print("1D array of 8 zeros:")
print(a)

print("\n 4x4 array of ones:")
print(b)

print("\n 3x3 matrix of zeros:")
print(c)

1D array of 8 zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

 4x4 array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy  as np

# a) Numbers from 0 to 20
a = np.arange(0,21,1)

# b) Even Number from 10 to 50
b = np.arange(10,51,2)

# c) Number from 5 to 100 with step of 5
c = np.arange(5,101,5)

print("a) Number from 0 to 20 :")
print(a)

print("\nb) Even numbers from 10 to 50:")
print(b)

print("\nc) Numbers from 5 to 100 with step of 5:")
print(c)

a) Number from 0 to 20 :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

b) Even numbers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

c) Numbers from 5 to 100 with step of 5:
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
import numpy as np

# a) 10 equally spaced numbers between 0 and 5
arr1 = np.linspace(0, 5, 10)
print("Array 1:")
print(arr1)
print("Length:", len(arr1))

# b) 15 equally spaced numbers between -10 and 10
arr2 = np.linspace(-10, 10, 15)
print("\nArray 2:")
print(arr2)
print("Length:", len(arr2))

Array 1:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

Array 2:
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [5]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nMatrix Addition:\n", A + B)
print("\nMatrix Multiplication:\n", A @ B)
print("\nElement-wise Multiplication:\n", A * B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [6]:
import numpy as np

arr = np.random.randint(1, 101, (4,4))

print("Matrix:\n", arr)

print("\nShape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Minimum:", arr.min())
print("Maximum:", arr.max())

Matrix:
 [[61 65 89 93]
 [86  2 17 16]
 [10 59 77 44]
 [63 64 95 63]]

Shape: (4, 4)
Dimension: 2
Size: 16
Data Type: int64
Minimum: 2
Maximum: 95


In [ ]:
import numpy as np

# a) 1D array of 10 random numbers between 0 and 1
arr1 = np.random.rand(10)

# b) 3x3 matrix of random numbers from standard normal distribution
arr2 = np.random.randn(3, 3)

# c) 4x5 array of random integers between 10 and 50
arr3 = np.random.randint(10, 51, (4, 5))

# Print all arrays with proper headings
print("a) 1D Array of 10 Random Numbers (0 to 1):")
print(arr1)

print("\nb) 3x3 Matrix of Random Numbers (Standard Normal Distribution):")
print(arr2)

print("\nc) 4x5 Matrix of Random Integers (10 to 50):")
print(arr3)

a) 1D Array of 10 Random Numbers (0 to 1):
[0.06344313 0.53318073 0.12284805 0.30361834 0.20084341 0.36606399
 0.68480221 0.11347106 0.86156022 0.44890501]

b) 3x3 Matrix of Random Numbers (Standard Normal Distribution):
[[-0.70611701  1.47713777 -0.42302441]
 [ 1.33950877  0.01605119  1.71250206]
 [ 1.17076866 -0.84617616  1.87908551]]

c) 4x5 Matrix of Random Integers (10 to 50):
[[14 36 26 50 19]
 [43 38 39 44 17]
 [16 36 47 24 20]
 [32 46 35 24 28]]


In [ ]:
import numpy as np

# Create two vectors
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

# Addition
print("Addition:")
print(v1 + v2)

# Subtraction
print("\nSubtraction:")
print(v1 - v2)

# Element-wise Multiplication
print("\nElement-wise Multiplication:")
print(v1 * v2)

# Dot Product
print("\nDot Product:")
print(np.dot(v1, v2))

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100


In [ ]:
import numpy as np

# Generate a 1D array of 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

# Reshape into a 4x5 matrix
matrix = arr.reshape(4, 5)

# Print the matrix
print("4x5 Matrix:")
print(matrix)

# Statistics
print("\nSum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Maximum value in each row
print("\nMaximum value in each row:")
print(np.max(matrix, axis=1))

4x5 Matrix:
[[31 29 22  2 21]
 [23 25 41 47 34]
 [13  7 47  8 31]
 [22 32 22 17 30]]

Sum: 504
Mean: 25.2
Standard Deviation: 11.964948808916816

Maximum value in each row:
[31 47 47 32]


In [ ]:
import numpy as np

try:
    # Ask the user for the number of random numbers
    n = int(input("Enter how many random numbers to generate: "))

    if n <= 0:
        print("Please enter a positive number.")

    else:
        # Generate random numbers between 10 and 100
        arr = np.random.randint(10, 101, n)

        # Print the array
        print("\nGenerated Array:")
        print(arr)

        # Statistics
        print("\nMean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Standard Deviation:", np.std(arr))
        print("Minimum:", np.min(arr))
        print("Maximum:", np.max(arr))

        # Reshape into a 2D array if possible
        if n % 2 == 0:
            matrix = arr.reshape(2, n // 2)
            print("\n2D Array:")
            print(matrix)

            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))
        else:
            print("\nCannot reshape into a 2D array because the number of elements is not even.")

except ValueError:
    print("Invalid input! Please enter an integer.")

Enter how many random numbers to generate: 10

Generated Array:
[70 25 42 47 95 51 79 89 34 25]

Mean: 55.7
Median: 49.0
Standard Deviation: 24.580683473003756
Minimum: 25
Maximum: 95

2D Array:
[[70 25 42 47 95]
 [51 79 89 34 25]]

Row-wise Sum:
[279 278]
